FROM centos

RUN yum update -y ; yum install -y java maven ; mvn archetype:generate -B -DarchetypeGroupId=am.ik.archetype -DarchetypeArtifactId=spring-boot-blank-archetype -DarchetypeVersion=1.0.6 -DgroupId=com.example -DartifactId=hajiboot -Dversion=1.0.0-SNAPSHOT

EXPOSE 8080

CMD cd /hajiboot ; mvn spring-boot:run